### ISSUE TITLE
SIGSEGV, Segmentation fault when builtin 'head' function receives too many arguments

### ISSUE THREAD

**Issue by Mr-Kumar-Abhishek** [Mr-Kumar-Abhishek/zuzeelik#25]
SIGSEGV, Segmentation fault when 'head' function receives too many arguments. (#24)

```
zuzeelik [ version: v0.0.0-0.5.0 ] 

Press Ctrl+C to Exit 

zuzeelik> head [2 3 ] [3 4]

Abstract Syntax Tree:

> 
  regex 
  expression|symbol|string:1:1 'head'
  quote|> 
    char:1:6 '['
    expression|number|regex:1:7 '2'
    expression|number|regex:1:9 '3'
    char:1:11 ']'
  quote|> 
    char:1:13 '['
    expression|number|regex:1:14 '3'
    expression|number|regex:1:16 '4'
    char:1:17 ']'
  regex 


Total number of nodes: 14

Received input: (head [2.000000 3.000000] [3.000000 4.000000])

Program received signal SIGSEGV, Segmentation fault.
0x080494e3 in builtin_head ()
(gdb) backtrace
#0  0x080494e3 in builtin_head ()
#1  0x08049c33 in builtin_lookup ()
#2  0x08049fd7 in zval_evaluate_sym_expression ()
#3  0x08049ffe in zval_evaluate ()
#4  0x0804a204 in main ()

```

**Comment by Mr-Kumar-Abhishek** [comment]
Fix for this is already in progress. Testing remains.

**Comment by Mr-Kumar-Abhishek** [comment]
commit ed7d9ba closes this issue.
